### ISSUE TITLE
Having this bug on the new update for 1.16.5 forge 36.1.25

### ISSUE THREAD

**Issue by Mr-Syntax** [Silverminer007/Shrines#10]
the 2 new versions give me this bug, its a shame cause the version before this the harbour spawn is kinda bugged

[06:43:17] [Server thread/ERROR]: Exception caught during firing event: null
	Index: 20
	Listeners:
		0: NORMAL
		1: ASM: class net.mehvahdjukaar.supplementaries.events.ServerEvents onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		2: ASM: class tictim.paraglider.event.ParagliderEventHandler onLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		3: net.minecraftforge.eventbus.EventBus$$Lambda$3036/540040261@7bd25dbe
		4: ASM: class net.mehvahdjukaar.supplementaries.world.data.GlobeData onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		5: ASM: class net.silentchaos512.scalinghealth.event.CommonEvents onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		6: ASM: class net.pavocado.exoticbirds.ForgeEventSubscriber onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		7: ASM: sereneseasons.handler.season.SeasonHandler@44de98bc onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		8: ASM: net.minecraftforge.common.ForgeInternalHandler@b2295e8 playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		9: ASM: class de.intektor.mods.grapple_hooks.CommonEventHandler playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		10: ASM: class hunternif.mc.impl.atlas.forge.ForgeEvent playerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		11: ASM: class greekfantasy.event.CommonForgeEventHandler onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		12: ASM: class com.ldtteam.structurize.event.EventSubscriber onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		13: ASM: class com.teammetallurgy.atum.misc.event.AtumEventListener onPlayerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		14: ASM: class net.blay09.mods.kleeslabs.network.SyncHandler onLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		15: ASM: net.aurelj.dungeonsarise.DungeonsAriseModVariables@6dada31a onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		16: ASM: class com.github.clevernucleus.playerex.init.EventHandler onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		17: ASM: class twilightforest.TFEventListener playerLogsIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		18: ASM: class twilightforest.TFEventListener onClientConnect(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		19: ASM: class com.baguchan.enchantwithmob.CommonEventHandler onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		20: ASM: class com.silverminer.shrines.events.CommonEvents$ForgeEventBus onPlayerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		21: ASM: class net.blay09.mods.waystones.handler.LoginHandler onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		22: ASM: com.tom.cpm.common.ServerHandler@262608e4 onPlayerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		23: ASM: net.mcreator.villageemployment.VillageEmploymentModVariables@7d2c2d23 onPlayerLoggedInSyncPlayerVariables(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		24: ASM: class its_meow.betteranimalsplus.BetterAnimalsPlusMod onPlayerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		25: net.minecraftforge.eventbus.EventBus$$Lambda$3036/540040261@680aebeb
		26: ASM: class com.oblivioussp.spartanshields.ModSpartanShields onPlayerLogIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		27: ASM: class com.ma.progression.ProgressionEventHandler onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		28: ASM: class slimeknights.tconstruct.shared.PlayerDataEvents onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		29: ASM: class com.minecolonies.coremod.event.EventHandler onPlayerEnterWorld(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		30: ASM: class com.minecolonies.coremod.event.FMLEventHandler onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		31: ASM: class corgitaco.enchancedcelestials.EnhancedCelestials$EnhancedCelestialsEvents onPlayerJoined(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		32: ASM: class net.valhelsia.valhelsia_core.event.PlayerJoinWorldListener onPlayerJoinWorld(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		33: ASM: snownee.kiwi.contributor.Contributors@295d1a45 onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		34: ASM: vazkii.quark.content.tweaks.module.AutomaticRecipeUnlockModule@26cb2dd5 onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		35: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@6668781 playerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		36: ASM: squeek.appleskin.network.SyncHandler@7fa02044 onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		37: net.minecraftforge.eventbus.EventBus$$Lambda$3036/540040261@4eb82ef
		38: ASM: tschipp.carryon.common.event.ItemEvents@65c66096 onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		39: net.minecraftforge.eventbus.EventBus$$Lambda$3036/540040261@3614d559
		40: ASM: dev.gigaherz.toolbelt.slot.BeltExtensionSlot$EventHandlers@23765d95 joinWorld(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		41: ASM: team.creative.creativecore.common.config.event.ConfigEventHandler@23d7d19e playerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		42: ASM: pregenerator.common.manager.ServerManager@6bd7b58a onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
java.lang.NullPointerException
	at com.silverminer.shrines.utils.network.SCustomStructuresPacket.<init>(SCustomStructuresPacket.java:38)
	at com.silverminer.shrines.utils.custom_structures.Utils.toPacket(Utils.java:275)
	at com.silverminer.shrines.utils.custom_structures.Utils.sendToClients(Utils.java:264)
	at com.silverminer.shrines.utils.custom_structures.Utils.onChanged(Utils.java:254)
	at com.silverminer.shrines.events.CommonEvents$ForgeEventBus.onPlayerJoin(CommonEvents.java:107)
	at net.minecraftforge.eventbus.ASMEventHandler_1995_ForgeEventBus_onPlayerJoin_PlayerLoggedInEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2625/1461698470.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:44)
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:231)
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118)
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at net.minecraft.server.MinecraftServer$$Lambda$30586/1581505365.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

[06:43:17] [Netty Local Client IO #0/INFO]: [projectvibrantjourneys.init.PVJWorldGen:addFallenTreeFeatures:176]: java.lang.NullPointerException
[06:43:17] [Server thread/FATAL]: Preparing crash report with UUID e1ab8982-7e8c-4b4d-8640-cf36bc05f151
[06:43:17] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking memory connection
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:137) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$30586/1581505365.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
	at com.silverminer.shrines.utils.network.SCustomStructuresPacket.<init>(SCustomStructuresPacket.java:38) ~[?:1.16.5-1.8.1-Beta2]
	at com.silverminer.shrines.utils.custom_structures.Utils.toPacket(Utils.java:275) ~[?:1.16.5-1.8.1-Beta2]
	at com.silverminer.shrines.utils.custom_structures.Utils.sendToClients(Utils.java:264) ~[?:1.16.5-1.8.1-Beta2]
	at com.silverminer.shrines.utils.custom_structures.Utils.onChanged(Utils.java:254) ~[?:1.16.5-1.8.1-Beta2]
	at com.silverminer.shrines.events.CommonEvents$ForgeEventBus.onPlayerJoin(CommonEvents.java:107) ~[?:1.16.5-1.8.1-Beta2]
	at net.minecraftforge.eventbus.ASMEventHandler_1995_ForgeEventBus_onPlayerJoin_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2625/1461698470.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:44) ~[?:?]
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:231) ~[?:?]
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118) ~[?:?]
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65) ~[?:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222) ~[?:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?]
	... 7 more
[06:43:17] [Netty Local Client IO #0/INFO]: [projectvibrantjourneys.init.PVJWorldGen:addFallenTreeFeatures:176]: java.lang.NullPointerException

**Comment by Silverminer007** [comment]
Please tr yout with Beta4 and close this issue if it works now
Note that the config GUI doesn't work on servers right now. Also in multiplayer sessions, you can only change structures from your client right now

**Comment by Silverminer007** [comment]
Next stable which fixes this bug is out, so i've closed it
