### ISSUE TITLE
Crash when generating chunks

### ISSUE THREAD

**Issue by NighthowlerStudios** [Silverminer007/Shrines#22]
**Describe the bug**
the server (and singleplayer) will suddenly crash when a shrines structure attempts to generate.  It's a null pointer exception.

**To Reproduce**
(it's random, only occurs when generating lots of chunks)

**Version (please complete the following information):**
 - OS: Windows 10 21H1

 - Forge Version 36.2.8
 - Mod Version 2.0.0 BETA 2

**Additional context**
[crash-2021-11-13_14.48.30-server.txt](https://github.com/Silverminer007/Shrines/files/7532269/crash-2021-11-13_14.48.30-server.txt)

**Comment by NighthowlerStudios** [comment]
java.lang.NullPointerException: Exception generating new chunk
	at net.minecraft.world.gen.feature.jigsaw.JigsawManager.func_242837_a(SourceFile:266) ~[?:?] {re:classloading}
	at com.silverminer.shrines.structures.ShrinesStructure$Start.generatePieces(ShrinesStructure.java:187) ~[?:1.16.5-2.0.0-Beta2] {re:classloading}
	at com.silverminer.shrines.structures.ShrinesStructure$Start.func_230364_a_(ShrinesStructure.java:149) ~[?:1.16.5-2.0.0-Beta2] {re:classloading}

**Comment by NighthowlerStudios** [comment]
Seems to be related to the config after changes in SNAPSHOT 16, it just makes it crash because start is empty.

**Comment by NighthowlerStudios** [comment]
it is related to the path the new configs are.  the file is not found on load and instead of crashing on that, it crashes on the null
