### ISSUE TITLE
Mod Freezes Dedicated Server every few seconds due to config saving

### ISSUE THREAD

**Issue by VirdsEyeBiew** [Silverminer007/Shrines#31]
[22:50:02] [Server thread/INFO] [co.si.sh.ev.CommonEvents/]: []
[22:50:02] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:116]: java.io.FileNotFoundException: config\theabyss2.json (The system cannot find the file specified)
[22:50:02] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:116]: 	at java.io.FileInputStream.open0(Native Method)
[22:50:02] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:116]: 	at java.io.FileInputStream.open(Unknown Source)
[22:50:02] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:116]: 	at java.io.FileInputStream.<init>(Unknown Source)
[22:50:02] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:116]: 	at java.io.FileReader.<init>(Unknown Source)
[22:50:02] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:116]: 	at net.yezon.theabyss.procedures.ReadConfigFileProcedure.executeProcedure(ReadConfigFileProcedure.java:50)
[22:50:02] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:116]: 	at net.yezon.theabyss.procedures.ReadConfigFileProcedure$GlobalTrigger.onPlayerLoggedIn(ReadConfigFileProcedure.java:36)
[22:50:02] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:116]: 	at net.minecraftforge.eventbus.ASMEventHandler_1501_GlobalTrigger_onPlayerLoggedIn_PlayerLoggedInEvent.invoke(.dynamic)
[22:50:02] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:116]: 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
[22:50:02] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:116]: 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
[22:50:02] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:116]: 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
[22:50:02] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:116]: 	at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:44)
[22:50:02] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:116]: 	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:232)
[22:50:02] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:116]: 	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118)
[22:50:02] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:116]: 	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65)
[22:50:02] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:116]: 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222)
[22:50:02] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:116]: 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134)
[22:50:02] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:116]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865)
[22:50:02] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:116]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291)
[22:50:02] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:116]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
[22:50:02] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:116]: 	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
[22:50:02] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:116]: 	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
[22:50:02] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:116]: 	at java.lang.Thread.run(Unknown Source)
[22:51:22] [Server thread/INFO] [co.si.sh.ut.cu.Utils/]: Saving config options on path: C:\Users\Tyler\Desktop\server\shrines-saves
[22:51:22] [Server thread/INFO] [co.si.sh.ut.cu.Utils/]: Saving config options on path: C:\Users\Tyler\Desktop\server\shrines-saves
[22:51:22] [Server thread/INFO] [co.si.sh.ut.cu.Utils/]: Saving config options on path: C:\Users\Tyler\Desktop\server\shrines-saves
[22:51:22] [Server thread/INFO] [co.si.sh.ut.cu.Utils/]: Saving config options on path: C:\Users\Tyler\Desktop\server\shrines-saves
[22:51:22] [Server thread/INFO] [co.si.sh.ut.cu.Utils/]: Saving config options on path: C:\Users\Tyler\Desktop\server\shrines-saves
[22:51:22] [Server thread/INFO] [co.si.sh.ut.cu.Utils/]: Saving config options on path: C:\Users\Tyler\Desktop\server\shrines-saves
[22:51:22] [Server thread/INFO] [co.si.sh.ut.cu.Utils/]: Saving config options on path: C:\Users\Tyler\Desktop\server\shrines-saves
[22:51:22] [Server thread/INFO] [co.si.sh.ut.cu.Utils/]: Saving config options on path: C:\Users\Tyler\Desktop\server\shrines-saves
[22:51:22] [Server thread/INFO] [co.si.sh.ut.cu.Utils/]: Saving config options on path: C:\Users\Tyler\Desktop\server\shrines-saves
[22:51:22] [Server thread/INFO] [co.si.sh.ut.cu.Utils/]: Saving config options on path: C:\Users\Tyler\Desktop\server\shrines-saves
[22:51:22] [Server thread/INFO] [co.si.sh.ut.cu.Utils/]: Saving config options on path: C:\Users\Tyler\Desktop\server\shrines-saves
[22:51:22] [Server thread/INFO] [co.si.sh.ut.cu.Utils/]: Saving config options on path: C:\Users\Tyler\Desktop\server\shrines-saves
[22:51:22] [Server thread/INFO] [co.si.sh.ut.cu.Utils/]: Saving config options on path: C:\Users\Tyler\Desktop\server\shrines-saves
[22:51:22] [Server thread/INFO] [co.si.sh.ut.cu.Utils/]: Saving config options on path: C:\Users\Tyler\Desktop\server\shrines-saves
[22:51:22] [Server thread/INFO] [co.si.sh.ut.cu.Utils/]: Saving config options on path: C:\Users\Tyler\Desktop\server\shrines-saves
[22:56:22] [Server thread/INFO] [co.si.sh.ut.cu.Utils/]: Saving config options on path: C:\Users\Tyler\Desktop\server\shrines-saves
[22:56:22] [Server thread/INFO] [co.si.sh.ut.cu.Utils/]: Saving config options on path: C:\Users\Tyler\Desktop\server\shrines-saves
[22:56:22] [Server thread/INFO] [co.si.sh.ut.cu.Utils/]: Saving config options on path: C:\Users\Tyler\Desktop\server\shrines-saves
[22:56:22] [Server thread/INFO] [co.si.sh.ut.cu.Utils/]: Saving config options on path: C:\Users\Tyler\Desktop\server\shrines-saves
[22:56:22] [Server thread/INFO] [co.si.sh.ut.cu.Utils/]: Saving config options on path: C:\Users\Tyler\Desktop\server\shrines-saves
[22:56:22] [Server thread/INFO] [co.si.sh.ut.cu.Utils/]: Saving config options on path: C:\Users\Tyler\Desktop\server\shrines-saves
[22:56:22] [Server thread/INFO] [co.si.sh.ut.cu.Utils/]: Saving config options on path: C:\Users\Tyler\Desktop\server\shrines-saves
[22:56:22] [Server thread/INFO] [co.si.sh.ut.cu.Utils/]: Saving config options on path: C:\Users\Tyler\Desktop\server\shrines-saves
[22:56:22] [Server thread/INFO] [co.si.sh.ut.cu.Utils/]: Saving config options on path: C:\Users\Tyler\Desktop\server\shrines-saves
[22:56:22] [Server thread/INFO] [co.si.sh.ut.cu.Utils/]: Saving config options on path: C:\Users\Tyler\Desktop\server\shrines-saves
[22:56:22] [Server thread/INFO] [co.si.sh.ut.cu.Utils/]: Saving config options on path: C:\Users\Tyler\Desktop\server\shrines-saves
[22:56:22] [Server thread/INFO] [co.si.sh.ut.cu.Utils/]: Saving config options on path: C:\Users\Tyler\Desktop\server\shrines-saves
[22:56:22] [Server thread/INFO] [co.si.sh.ut.cu.Utils/]: Saving config options on path: C:\Users\Tyler\Desktop\server\shrines-saves
[22:56:22] [Server thread/INFO] [co.si.sh.ut.cu.Utils/]: Saving config options on path: C:\Users\Tyler\Desktop\server\shrines-saves
[22:56:22] [Server thread/INFO] [co.si.sh.ut.cu.Utils/]: Saving config options on path: C:\Users\Tyler\Desktop\server\shrines-saves

**Comment by Silverminer007** [comment]
Please update either to a more recent version like 2.0.0 (Currently Beta state but stable soon) or disable autosave in properties in shrines saves

**Comment by Silverminer007** [comment]
I am closing this issue as 1.8.1 or lower will no longer receive support. Please upgrade to a newer version.
https://silverminer007.github.io/ShrinesWiki/wiki/en_us/users/UpdateTo2.0.0From1.8.1.html
or
https://silverminer007.github.io/ShrinesWiki/wiki/en_us/users/UpdateTo3.x.xFrom1.8.1.html
